### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [KnowItCo/knowit#2]
In your script:

https://github.com/KnowItCo/knowit/blob/master/server/db/create.js

you forgot to define function `sql`, like it was done in the example [here](https://github.com/vitaly-t/pg-promise#query-files):

```js
function sql(file) {
    return new pgp.QueryFile(file, {debug: true, minify: true});
}
```

**Comment by iam-peekay** [comment]
@vitaly-t thank you. I fixed it :)
